spring:
  profiles:
    active: ${environment}

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://ec2-54-243-228-140.compute-1.amazonaws.com:5432/d22bbvm7tp5lvq
    username: iesnqowkznvcgv
    password: 4f7c9bc40ba76663689ce883967e43b786f2e4d0680a4918caa6f61568cc3efe
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://ec2-54-235-94-36.compute-1.amazonaws.com:5432/dbr965nocti8ei
    username: ioldyoqppzwqqw
    password: 8654f1f45fb3698366fa3e3533b4d45133f943959b4b9ee0fcaa018f2a9065dc
    driver-class-name: org.postgresql.Driver

---